/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pratica4;

public class Library {
    public boolean someLibraryMethod() {
    	int a = 1;
    	int b = 4;
        return a + b == 4;
    }
}
